# Generated by Django 3.2.3 on 2022-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20220707_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
