# Generated by Django 3.2.3 on 2022-07-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20220720_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='crowdfund',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='health',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
