# Generated by Django 3.2.3 on 2022-07-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20220720_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
