# Generated by Django 3.2.3 on 2022-07-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_alter_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
