# Generated by Django 3.2.3 on 2022-07-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='forest',
            field=models.CharField(default='Not Worthy', max_length=50),
        ),
    ]
